variable "region" { default = "us-east-2" }

variable "environment" {
  type = string
  default = "project_name" # bus_unit_name, project_name, dev, stage, prod, etc
  description = "Environment name"
  validation {
    condition = length(var.environment) > 1
    error_message = "Environment name must be at least 3 characters."
  }
}

variable sg_ingress_cidr {
  type = list
  description = "List of allowed ingress cidr patterns for the DSF hub instance"
  default = ["1.2.3.4/32", "172.20.0.0/16"]
}

variable "key_pair" {
  type = string
  description = "key pair for DSF hub instance. This key must be generated by by the hub module and present on the local disk"
  default = "your-key-name-here"
}

variable "s3_bucket" { default = "your-s3-bucket-name-here" }

