---
- name: Federate
  hosts: gws
  gather_facts: yes
  tasks:
    - name: is gw installed
      stat:
        path: "$JSONAR_LOCALDIR/dispatcher/dispatcher.conf"
      become: true
    - name: is hub installed
      stat:
        path: "$JSONAR_LOCALDIR/dispatcher/dispatcher.conf"
      delegate_to: hub
      run_once: true
      become: true
    
    - name: is federated
      shell: if grep Remote_{{ hostvars[inventory_hostname]['ansible_ssh_host'] }} /data_vol/sonar-dsf/jsonar/local/dispatcher/dispatcher.conf &>/dev/null; then echo FEDERATED; fi
      args:
        executable: /bin/bash
      changed_when: false
      become: true
      delegate_to: hub
      register: is_federated
    - name: print is federated
      debug:
        var: is_federated.stdout
    - block:
      - name: Hub federation
        shell: |
          source /etc/sysconfig/jsonar
          $JSONAR_BASEDIR/bin/federated warehouse {{ hostvars['hub']['ansible_ssh_host'] }} {{ hostvars[inventory_hostname]['ansible_ssh_host'] }}
        args:
          executable: /bin/bash
        throttle: 1 # Federation on hub doesn't support concurrency
        become: true
        delegate_to: hub
        register: warehouse_output
      - debug:
          var: warehouse_output.stdout_lines
      - name: GW federation
        shell: |
          source /etc/sysconfig/jsonar
          sudo $JSONAR_BASEDIR/bin/federated remote
        args:
          executable: /bin/bash
        become: true
        register: gw_output
      - debug:
          var: gw_output.stdout_lines
      when: is_federated.stdout != "FEDERATED"