variable "region" {
  type = string
}

variable "admin_password" {
  type = string
  sensitive = true
}

variable "name" {
  type = string
  default = "imperva-dsf-agentless-gw"
}

variable "subnet_id" {
  type = string
  description = "Subnet id for the DSF agentless gw ec2 instance"
}

variable "instance_type" {
  type = string
  default = "t2.2xlarge"
  description = "Ec2 instance type for the DSF agentless gw"
}

variable "disk_size" {
  default = 150
  validation {
    condition     = var.disk_size >= 150
    error_message = "DSF agentless gw disk size must be at least 150GB"
  }
}

variable "key_pair" {
  type = string
  description = "key pair for DSF agentless gw ec2 instance. This key must be generated by by the hub module and present on the local disk."
}
